### ISSUE TITLE
ESP renewable Configuration

### ISSUE THREAD

**Issue by maxiwoj** [Chimstaz/SmartHome#9]
ESPs don't remember their configuration after disconnected from power source. Introduce system, where once provided configuration is renewable for ESPs even on reset.

**Comment by Chimstaz** [comment]
It should be in EEPROM memory, or as retained message on MQTT broker? I'm voting for retained message, because EEPROM has limited writing cycles. Module without broker is useless anyway. I would use EEPROM for holding ssid and password for network and possibly broker ip address. Everything else could be on broker, so module will download it right after connection.

**Comment by maxiwoj** [comment]
All configuration messages should be published as retained messages then. What about ssid and password? I think the best option would be to allow a user to set this over USB port from console and keep it in the EEPROM.

**Comment by Chimstaz** [comment]
Done in #12
